### ISSUE TITLE
10.12 error?

### ISSUE THREAD

**Issue by juliankauai** [ayunav/NeverlateApp#4]
looks great and i want to try it out. got an error in compiling. thanks - julian

<img width="1159" alt="screen shot 2016-09-27 at 11 54 46 am" src="https://cloud.githubusercontent.com/assets/1791443/18887519/43f0147e-84a9-11e6-81a3-0c41ba916457.png">

**Comment by ayunav** [comment]
Hi @juliankauai , the project requires Venmo credentials to run (app id and app secret id). Do you have those?
